### ISSUE TITLE
autoprefixer not showing up at all 

### ISSUE THREAD

**Issue by nickfmc** [sindresorhus/atom-autoprefixer#15]
I installed autoprefixer, however no autoprefixer option shows up in my command palette I've reinstalled a bunch of times and tried everthing I can think of, but other than it being in my installed packages list there is no sign of it?

windows 8.1 
atom 0.205.0

**Comment by sindresorhus** [comment]
I just tried reinstalling the plugin in atom 0.205.0 and works fine for me on OS X.

Maybe you had some install corruption or something. Try reinstalling the plugin.

**Comment by nickfmc** [comment]
ya, as I mentioned  I've reinstalled a bunch of times, is there anything left behind after install I should clean out? no issues with any other plugins

**Comment by nickfmc** [comment]
Tried to reinstall after the last Atom update and I get this:

[Enter steps to reproduce below:]

1. ... Try to install plugin
2. ...

**Atom Version**: 0.207.0
**System**: Microsoft Windows 8.1
**Thrown From**: [autoprefixer](https://github.com/sindresorhus/atom-autoprefixer) package, v2.2.3


### Stack Trace

Uncaught Error: Cannot find module '../package'

```
At module.js:330

Error: Cannot find module '../package'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Nick\.atom\packages\autoprefixer\node_modules\autoprefixer-core\node_modules\postcss\lib\processor.js:66:31)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Nick\.atom\packages\autoprefixer\node_modules\autoprefixer-core\node_modules\postcss\lib\postcss.js:11:18)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Nick\.atom\packages\autoprefixer\node_modules\autoprefixer-core\lib\autoprefixer.js:7:13)
  at Object.<anonymous> (C:\Users\Nick\.atom\packages\autoprefixer\node_modules\autoprefixer-core\lib\autoprefixer.js:88:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Nick\.atom\packages\autoprefixer\index.js:2:20)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:707:34)
  at Package.module.exports.Package.activateConfig (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:255:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:201:12)
  at C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:235:24
  at C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\emissary\lib\emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\emissary\lib\emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\emissary\lib\emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:546:19)
  at C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:369:26
  at exit (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:53:16)
  at triggerExitCallback (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Nick\AppData\Local\atom\app-0.207.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  2x -5:39.4.0 core:backspace (atom-text-editor.editor.is-focused)
  7x -5:33 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -5:25.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -5:25 core:delete (atom-text-editor.editor.is-focused)
     -5:23.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:23.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:46.4.0 core:delete (atom-text-editor.editor.is-focused)
     -4:45.5.0 core:save (atom-text-editor.editor.is-focused)
     -4:41 core:backspace (atom-text-editor.editor.is-focused)
     -4:40.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:16.2.0 core:copy (atom-text-editor.editor.is-focused)
     -1:13.1.0 command-palette:toggle (atom-text-editor.editor)
 12x -1:10.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:02.5.0 settings-view:open (atom-text-editor.editor.mini)
  2x -0:54.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:49.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "SFTP-deployment"
    ],
    "themes": [
      "accents-ui",
      "oceanic-reef-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v0.2.0
color-picker, v2.0.4
docblockr, v0.7.2
emmet, v2.3.10
file-icons, v1.5.7
less-than-slash, v0.6.0
linter, v0.12.6
linter-jshint, v0.1.6
linter-php, v0.0.15
oceanic-reef-syntax, v0.5.0
pigments, v0.4.5
project-manager, v1.15.10
sass-autocompile, v0.7.0
symbols-tree-view, v0.9.3
tool-bar, v0.1.5
tool-bar-main, v0.0.8
wordpress-api, v1.2.1

# Dev
No dev packages
```
