### ISSUE TITLE
Uncaught Error: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by CyrusDwayne** [sindresorhus/atom-autoprefixer#54]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [autoprefixer](https://github.com/sindresorhus/atom-autoprefixer) package 3.7.1

### Stack Trace

Uncaught Error: Cannot find module 'postcss'

```
At module.js:545

Error: Cannot find module 'postcss'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.29.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/autoprefixer/index.js:13:16)
    at /packages/autoprefixer/index.js:130:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.29.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.29.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:782:33)
    at Package.activateConfig (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/package-card.js:794:40)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/package-card.js:439:22)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/package-card.js:431:18)
    at ~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/package-card.js:728:22
    at ~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/package-card.js:811:17
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/package-manager.js:659:33)
    at ~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/package-manager.js:498:32
    at exit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.29.0/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (~/AppData/Local/atom/app-1.29.0/resources/app/src/buffered-process.js:297:15)
```

### Commands

```
     -9:58 core:save (input.hidden-input)
     -9:55.4.0 snippets:previous-tab-stop (input.hidden-input)
     -9:55.4.0 editor:outdent-selected-rows (input.hidden-input)
     -9:54.7.0 core:save (input.hidden-input)
     -9:29.1.0 snippets:previous-tab-stop (input.hidden-input)
     -9:29.1.0 editor:outdent-selected-rows (input.hidden-input)
  2x -9:28.5.0 core:move-up (input.hidden-input)
     -9:27.4.0 snippets:next-tab-stop (input.hidden-input)
     -9:27.4.0 snippets:expand (input.hidden-input)
     -9:27.4.0 editor:indent (input.hidden-input)
  2x -9:25.7.0 core:save (input.hidden-input)
  3x -6:49.9.0 core:backspace (input.hidden-input)
     -6:25.5.0 core:save (input.hidden-input)
  2x -5:40.2.0 core:paste (span.syntax--text.syntax--html.syntax--basic)
     -5:19.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
autoprefixer 3.7.1 
todo-list 1.0.0 
todo-show 2.3.0 
```

**Comment by sindresorhus** [comment]
This is a problem with Atom not being able to install the plugin and has nothing to do specifically with this plugin.
