### ISSUE TITLE
Uncaught Error: Cannot find module 'postcss'Require stack:- $ATOM_HOME/packages/autoprefixer/in...

### ISSUE THREAD

**Issue by VelZeVSer** [sindresorhus/atom-autoprefixer#78]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Kali GNU/Linux
**Thrown From**: [autoprefixer](https://github.com/sindresorhus/atom-autoprefixer) package 4.3.0

### Stack Trace

Uncaught Error: Cannot find module 'postcss'
Require stack:
- /home/valery/.atom/packages/autoprefixer/index.js
- /usr/share/atom/resources/app.asar/static/index.html

```
At internal/modules/cjs/loader.js:800

Error: Cannot find module 'postcss'
Require stack:
- /home/valery/.atom/packages/autoprefixer/index.js
- /usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149207)
    at /packages/autoprefixer/index.js:58:16)
    at /packages/autoprefixer/index.js:143:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at requireModule (/usr/share/atom/resources/app/static/<embedded>:14:1195620)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3400284)
    at Package.activateConfig (/usr/share/atom/resources/app/static/<embedded>:11:3389572)
    at PackageManager.packageHasSettings (/usr/share/atom/resources/app/static/<embedded>:11:908520)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/static/<embedded>:14:2726600)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/static/<embedded>:14:2716868)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/static/<embedded>:14:2716691)
    at /usr/share/atom/resources/app/static/<embedded>:14:2724833
    at /usr/share/atom/resources/app/static/<embedded>:14:2726851
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1188366)
    at PackageManager.emitPackageEvent (/usr/share/atom/resources/app/static/<embedded>:11:917977)
    at /usr/share/atom/resources/app/static/<embedded>:11:915109
    at r (/usr/share/atom/resources/app/static/<embedded>:11:909639)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1194943)
    at /usr/share/atom/resources/app/static/<embedded>:14:1195097
    at Socket.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:1193699)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-i18n 0.26.1 
autoprefixer 4.3.0 
Hydrogen 2.16.3 
```

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
